### PR TITLE
Adding new timespan and editing through waveform

### PR DESCRIPTION
**Pull request by Dananji**
This fixes avalonmediasystem/avalon#3186

### CODE REVIEW

**Comment by adamjarling** [comment]
This all works really well.  Nice work!   The one thing I'm seeing that's not yet implemented is this "Done Looks Like" from the original issue:

> If the calculated End Time will overlap with another range, End Time should be the Begin Time of that adjoining range minus 0.001 ms.

The validation is accurate though.

**Comment by Dananji** [comment]
@adamjarling I actually wrote the logic to validate the end time initially, I think I might have removed that by mistake while I was doing some other changes. And pushed this without checking everything. Sorry about that. I wrote only one test case for the logic function, which totally omits a scenario where an end time overlaps existing timespan.

**Comment by adamjarling** [comment]
@Dananji Cool.  Even better if you have it, go ahead and plug it back in and let me know when it's set to have a look.  Nice work too.

**Comment by Dananji** [comment]
Sure, thanks Adam :+1: Will ping you once it's done.

**Comment by Dananji** [comment]
@adamjarling Done! And I used the trick you mentioned in the previous PR. That is really cool! :100:

**Pull request merged**
