### PR TITLE
Dananji peaks waveform

### PR DESCRIPTION
**Pull request by adamjarling**
@Dananji I made 2 commits to your branch.  Have a look, and see if they make sense or if you have any questions.  If you're ok with them, feel free to pull down the branch, and maybe we could update the CSS related comments I made to the original PR?   Then I think we're in pretty good shape.  

It looks great with a live player in there!

### CODE REVIEW

**Comment by adamjarling** [comment]
@Dananji Sounds good.  `dataUri` is still a property on the `peaksOptions` config object, same way as you originally had it set up.  If you need to play around with something new, feel free to experiment.  I'm not familiar yet, how Peaks.js works.

**Comment by Dananji** [comment]
Oh my bad. Didn't see it is there on the top. 
I changed the CSS according to your comments, replacing CSS selectors to 'classes' instead of 'id'. Can I do more regarding this?

**Comment by adamjarling** [comment]
No problem.  Yea, check out this PR, and have a look at my comments regarding CSS stuff.  https://github.com/avalonmediasystem/structured-metadata-editor-react/pull/3   

Once this is sorted, I guess we'll merge this PR, and close the original one for your branch.

**Comment by Dananji** [comment]
@adamjarling I committed the CSS fixes. Instead of using a container for the audio and the controls I introduced Bootstrap row class as you suggested.

**Comment by adamjarling** [comment]
@Dananji Sounds great, and looks good.  I made one small, last commit, building on your latest addition.  (Again, learning opportunity here...for both of us).  I pulled in the React Bootstrap package a while ago (https://react-bootstrap.github.io/).  These component libraries are a common pattern you'll see in modern React applications.   

Check out my commit.  React Bootstrap makes available `<Row>` and `<Col>` components, which I plugged in, just to show how we could keep building in a 'React' component library way.  These components are simply the library's wrappers for Bootstrap classes `.row` and `.col-md-xx`, etc.

If you're happy with the latest commit, I'd say go ahead and merge this branch in.

**Comment by Dananji** [comment]
@adamjarling Should I update the gh-pages with the new mege?

**Comment by adamjarling** [comment]
@Dananji Sure. It's been a while, but I think you can just run `yarn deploy` from your local machine (while on the `master` branch), and it will automatically push to the `gh-pages` branch and be live.

**Pull request merged**
