### PR TITLE
28 edit one timespan

### LINKED ISSUE #28: Enable editing one timespan at a time
### Description

Limit editing one timespan at a time in the inline forms.
A user can edit multiple timespans at a time, which breaks the validation logic for start and end times of the timespans.

### Done Looks Like

Two options:
1. Disable the other timespan edit buttons while a timespan is being edited
2. Block the rest of the items when an inline edit form is opened

child of samvera-labs/avalon-bundle#231

### PR DESCRIPTION
**Pull request by Dananji**
@adamjarling This fixes the issue of editing multiple timespans at once. The implementation blocks the entire structure when trying to edit multiple timespans at once.
This fixes #28

### CODE REVIEW

**Comment by adamjarling** [comment]
Also, looks like this branch will need to be rebased on master.  There might be conflict(s) after too.   Feel like taking a shot at that?

**Comment by Dananji** [comment]
@adamjarling I checked it out. It works fine on my end.
- When you get the blocking spinner and the alert, close the alert and the spinner goes away. And then you can close the opened inline form. Maybe I should add a button to that alert, so that the idea is clearer?
- And save button works as well. It doesn't show time changing in the form, but once it is saved, the new time appears on the structure.
I wonder what's happening. Maybe you don't get all the commits?

**Comment by adamjarling** [comment]
@Dananji I've pulled the latest commit from this branch, re-installed all yarn dependencies just to make sure.   Here's a screen shot of the text input field (for times) not appearing to update in the UI:

https://screencast.com/t/cldrKpMBxTeX

Let me know if this is not the same as your machine, then we can figure out why.

For the blocking of multiple edits at the same time, I now understand how it works with closing the alert box, then proceeding.  I'm wondering if we could find a less intrusive solution for this, perhaps something a bit more subtle like just disabling the "edit" icon on all non-active list items, while one timespan list item is being edited?  And maybe not pull in the extra `react-block-ui` package?   My initial reaction seeing the spinner is that an error occurred, or something bad happened that froze things up.   

Just my opinion here...if others are ok with it I'm cool with it too.  Maybe want to run this by @joncameron?

**Comment by adamjarling** [comment]
What might be the culprit here could be the conflicts?  I'm looking at the merge conflicts, resolving them locally in my dev environment, but you might be more familiar with the ins and outs of how these changes should apply. 

If you have a bit of time, mind rebasing this branch on `master` locally on your machine, resolve the conflicts for what you think is the most up-to-date way of handling code conflicts, then push up this branch again?

**Comment by Dananji** [comment]
@adamjarling Yeah, might be the conflicts. I will rebase this and push again.
Yeah, my initial approach was to do disable the edit buttons, but couldn't figure out a way. Maybe I'll give it another try. After working on the Peaks issue, I got a lot more insight into how to get things done using redux-store. Maybe we can use show-forms actions to do this?

**Comment by Dananji** [comment]
Yes, editing the timespans with the inline edit form works like that on my end as well. Because in this version of the code, I've wired the timespan editing only through Peaks waveform. So whenever you change time in the form and save it goes back to the original values. Sorry I didn't understand your question earlier. In this version timespans can be edited only through Peaks waveform.

**Comment by Dananji** [comment]
@adamjarling Now it's rebased on master, and it should work without any glitches. I will give another try on disabling the edit buttons.

**Comment by adamjarling** [comment]
@Dananji Got it.  Makes sense now that the data can only be edited through Peaks.js in this version.   We'll want to keep the functionality to have the times be editable from both the list item inline form, and also through Peak, right?   We can create another issue(s) to tackle that.

So for the scope of this ticket, yea we'll just keep the ability to edit one timespan at a time.  Can you try this approach?   

Maybe we create a new property in Redux store which keeps track of an edited item.  Since every list item has an `id` property, when the user starts editing a heading or timespan, an action creator fires off which passes the `id` of edited item.  When the inline form closes, the `id` value is removed from Redux store.  

Then we build into the `ListItem` component somewhere, the ability to check if a value exists for the `currentlyEditedItem` (or whatever we call it).  If a value does exist, and it's not the same id as the `ListItem`, then the button wrapping the icon has a `disabled` property applied to it. 

Does that seem like it makes sense?   I hate to make you do re-work but it we can handle this situation this way, and not have to pull in that `react-block-ui` package, I'd prefer that for the UX.   Yea or nea?   I'm open to your ideas as well.

**Comment by Dananji** [comment]
@adamjarling Yes, I agree that we have to be able to edit a timespan both through the inline form and Peaks. And I implemented that yesterday with the ticket #27 while bridging the gap between Peaks and React. I need to write some tests for that, after that I'll make a PR :)

Yeah, I totally agree. If there's a way of doing something without pulling in new packages, that'd be the best way. I used the concept in your comment and reused the same property used to block the ui from `show-forms` to disable and enable the edit buttons when a user starts editing an item.

One question: Do we block all the items? Or just the timespans?

**Comment by adamjarling** [comment]
@Dananji Ok, this is getting really close!  So it looks like the disabled visual state works as it should, but when the user clicks on a disabled button, the list item still has an action taken on it.  I'm pushing up a commit to fix it.  Then if you're good with it, I say go ahead and merge this one in.

**Comment by adamjarling** [comment]
@Dananji When you merge this today, please do the "Squash and merge" option, so we can keep the commit history as clean as possible.  I can't remember if I ever mentioned this, but I'd like to have each issue have only one commit, so we can always re-trace work if need be.   Thanks.

**Pull request merged**
